# Build phrase
FROM node:20.9.0-alpine3.18 as build
WORKDIR /app
COPY package*.json /app
RUN npm ci
COPY . .
RUN npm run build

# Serve phrase
FROM nginx:alpine
COPY nginx.conf /etc/nginx
COPY --from=build /app/dist/* /usr/share/nginx/html
EXPOSE 80 443
